site_name: Me Adota - Documentações
nav: 
  - Início: index.md
  - Metodologia: methodology.md
  - Requisitos: requirements.md
  - Design: design.md
  - Construção: construction.md
  - Testes: testing.md
  - Gerenciamento de Configuração: configuration.md
  - Gerenciamento de Projeto: management.md
  - Sobre: 
    - Informações: about/about.md
    - Contribuição: about/contributing.md
  - MkDOCS: mkdocs.md
theme:
  name: material
  language: en
  font:
    text: Ubuntu
    code: Ubuntu Mono

repo_name: Me-Adota/docs
repo_url: https://github.com/Me-Adota/docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Me-Adota
