site_name: Me Adota - Documentations

nav: 
  - Início: index.md
  - Metodologia: methodology.md
  - About: 
    - Global Information: about/about.md
    - Contributing: about/contributing.md
  - MkDOCS: mkdocs.md
theme:
  name: material
  language: en
  font:
    text: Ubuntu
    code: Ubuntu Mono

repo_name: Me-Adota/docs
repo_url: https://github.com/Me-Adota/docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Me-Adota
