site_name: Me Adota - Documentations
dev_addr: '0.0.0.0:8080'

theme:
  name: material
  language: en
  font:
    text: Ubuntu
    code: Ubuntu Mono

repo_name: Me-Adota/docs
repo_url: https://github.com/Me-Adota/docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Me-Adota
